### ISSUE TITLE
does not work ... initialisation problem

### ISSUE THREAD

**Issue by sandrobilbeisi** [cjkao/selectize#4]
hello @cjkao 

I tried building this and launching the /build/index.html in a browser but I get a set of broken controls
and the console reports a serious of errors
> **EXCEPTION: NoSuchMethodError: method not found: 'create' (self.__DartJqSelect.create is not a function. (In 'self.__DartJqSelect.create(z,v)', 'self.__DartJqSelect.create' is undefined))**
e8 — index.dart.js:8033
(anonymous function) — index.dart.js:7979
(anonymous function) — index.dart.js:7985:92
(anonymous function) — index.dart.js:6670
(anonymous function) — index.dart.js:2529
(anonymous function) — index.dart.js:7910
(anonymous function) — Anonymous Script 1 (line 2)
J — index.dart.js:3389
J — index.dart.js:7876
J — index.dart.js:6600
h8 — index.dart.js:6603
(anonymous function) — index.dart.js:6579
(anonymous function) — index.dart.js:2396
(anonymous function) — index.dart.js:2612
(anonymous function) — index.dart.js:2608
(anonymous function) — index.dart.js:7940
(anonymous function) — index.dart.js:2529
(anonymous function) — index.dart.js:7910
(anonymous function) — index.dart.js:7912
(anonymous function) — Anonymous Script 2 (line 2)
bc — index.dart.js:3394
$0 — index.dart.js:2914
bB — index.dart.js:2848
(anonymous function) — index.dart.js:2871
v_ — index.dart.js:2447
(anonymous function) — index.dart.js:2449
(anonymous function) — index.dart.js:2594
$0 — index.dart.js:1824
aY — index.dart.js:877
cM — index.dart.js:688
(anonymous function) — index.dart.js:1345
(anonymous function) — index.dart.js:1353

**Comment by sandrobilbeisi** [comment]
Screen shot
![screen shot 2016-12-05 at 09 50 03](https://cloud.githubusercontent.com/assets/755824/20878625/4ccb9930-bad0-11e6-926a-a101116dd305.png)

**Comment by cjkao** [comment]
angular2 transformer have been explicit turn off for non angular2 client, you need to modify `pubspec.yaml`  with 
```yaml
transformers:
- angular2:
    entry_points: web/index.dart
```

**Comment by sandrobilbeisi** [comment]
but that is already the way it is !
https://github.com/cjkao/selectize/blob/master/pubspec.yaml
